export const categories = [
  'all',
  'web',
  'psychology',
  'math',
  'native',
  'DSA',
  'system design',
  'UI/UX',
  'React ',
  'React Native',
  'Flutter',
  'RESTful api',
  'GrapgQL api',
  'Auth',
  'Database',
  'CI/CD',
  'problem solving',
  'comminucation',
  'Collaboration',
  'productivity',
  'Content creation',
  'Open source',
  'others',
];
